config/routes.rb
AppTemplate::Application.routes.draw do

  devise_for :admins, :path => "admin", :skip => [:registrations], :controllers => { :sessions => "admins/sessions" }
    as :admin do
      get 'admins/edit' => 'devise/registrations#edit', :as => 'edit_admin_registration'
      put 'admins' => 'devise/registrations#update', :as => 'admin_registration'
      get 'admin', :to => 'admin#index', :as => :admin_root
    end
  apipie
  namespace :api do
    namespace :v1 do
      
        resources :doctors
      
    end # v1

namespace :v2 do
      
        resources :doctors
      
    end # v2

namespace :v3 do
      
        resources :doctors
      
    end # v3
    
    namespace :v4 do
      
        resources :doctors
      
    end # v4
    
    # Mount rails engine gems.
    
  end

  namespace :admin do
    
      resources :doctors
    
  end
  get '/admin' => 'admin#index'

  root :to => 'root#index'
end

app/views/layouts/admin.html.haml
!!!
%html{lang: 'en', 'xml:lang' => 'en', xmlns: 'http://www.w3.org/1999/xhtml'}
  %head
    %title COH
    = stylesheet_link_tag 'admin'
    = javascript_include_tag 'admin'
    = csrf_meta_tags
  %body
    .header
      - if current_admin
        API v4: http://mysterious-cliffs-6188.herokuapp.com/api/v4
        \|
        = link_to 'Home', admin_root_path
        \|
        = link_to 'Documentation', apipie_path
        \|
        = link_to current_admin.email, edit_admin_registration_path
        \|
        = link_to "Sign out", destroy_admin_session_path, :method => :delete
    .container
      = yield

app/views/layouts/application.html.haml
!!!
%html{lang: 'en', 'xml:lang' => 'en', xmlns: 'http://www.w3.org/1999/xhtml'}
  %head
    %title COH
    = csrf_meta_tags
    %meta{:content => "width=device-width, initial-scale=1", :name => "viewport"}
    = content_tag :script, '', type: 'text/javascript', src: (request.ssl? ? 'https' : 'http') + '://maps.google.com/maps/api/js?sensor=true'
    = stylesheet_link_tag 'application', :media => 'all'
    = javascript_include_tag 'application'
    = javascript_tag "if (window.Ext) {Ext.Ajax.extraParams = { authenticity_token: '#{form_authenticity_token}' };}"
  %body
    .container
      = yield

app/views/layouts/documentation.html.haml
!!!
%html{lang: 'en', 'xml:lang' => 'en', xmlns: 'http://www.w3.org/1999/xhtml'}
  %head
    %title Funsies
    = stylesheet_link_tag 'admin'
    = javascript_include_tag 'admin'
    = Apipie.include_stylesheets
    = Apipie.include_javascripts
    = csrf_meta_tags
  %body
    .header
      - if current_admin
        API v1: http://localhost:3000/api/v1
        \|
        = link_to 'Home', admin_root_path
        \|
        = link_to 'Documentation', apipie_path
        \|
        = link_to current_admin.email, edit_admin_registration_path
        \|
        = link_to "Sign out", destroy_admin_session_path, :method => :delete
    .container
      = yield
  %footer
    = yield :apipie_footer